### ISSUE TITLE
请教一下群权限设置相关

### ISSUE THREAD

**Issue by CabbCat** [Karlatemp/LuckPerms-Mirai#107]
在使用部分插件时会有需要赋予某些群权限的情况
mirai原版使用perm add g12345 permission赋予
使用lp插件后尝试用/lp group default permission set PermissionInGroup group=1234567890命令给予权限但是发现无法实现，想请教一下是否是我用法有问题或者是使用的插件有问题...

具体正在使用的插件是[https://github.com/cssxsh/bilibili-helper]()以及[https://github.com/Colter23/bilibili-dynamic-mirai-plugin]()
其中涉及到的atall权限，权限id为xyz.cssxsh.mirai.plugin.bilibili-helper:live.atall以及top.colter.bilibili-dynamic-mirai-plugin:live.atall

**Comment by Karlatemp** [comment]
最新版本以修复此问题，如果还有问题请执行

/lp verbose on

并提供控制台日志

**Comment by CabbCat** [comment]
E/LuckPerms: WARMING: User 00000000-0000-0000-0000-000000000002{lnum=2} not loaded. Please report to https://github.com/Karlatemp/LuckPerms-Mirai

**Comment by Karlatemp** [comment]
是最新版lpm吗



---Original---
From: ***@***.***&gt;
Sent at: 2022年2月21日(Mon) AM10:18
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Karlatemp/LuckPerms-Mirai] 请教一下群权限设置相关 (Issue #107)




 
E/LuckPerms: WARMING: User 00000000-0000-0000-0000-000000000002{lnum=2} not loaded. Please report to https://github.com/Karlatemp/LuckPerms-Mirai

**Comment by CabbCat** [comment]
> 是最新版lpm吗
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2022年2月21日(Mon) AM10:18 To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [Karlatemp/LuckPerms-Mirai] 请教一下群权限设置相关 (Issue #107) E/LuckPerms: WARMING: User 00000000-0000-0000-0000-000000000002{lnum=2} not loaded. Please report to https://github.com/Karlatemp/LuckPerms-Mirai — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

是的，不过data文件没删除，有影响吗

**Comment by Karlatemp** [comment]
请打开 /lp verbose on并编辑 config/Console/Logger.yml 把 defaultLevel改成ALL

**Comment by CabbCat** [comment]
V/Bot.573704163: Group(435295993) <- [LP] 权限检查 > groupselector - xyz.cssxsh.mirai.plugin.bilibili-helper.live.atall - undefined[0m[m
V/Bot.573704163: Group(435295993) <- [LP] 权限检查 > groupselector - xyz.cssxsh.mirai.plugin.bilibili-helper.* - undefined[0m[m
V/Bot.573704163: Group(435295993) <- [LP] 权限检查 > groupselector - * - undefined[0m[m

但是default组里应该已经设置了权限
![image](https://user-images.githubusercontent.com/37258131/154895808-274eb886-963b-4d0d-8825-0cd1ffc44b0e.png)

**Comment by Karlatemp** [comment]
权限节点是 xyz.cssxsh.mirai.plugin.bilibili-helper.live.atall，并非冒号，lp统一使用点号，没有冒号

**Comment by CabbCat** [comment]
原来是这样，是我自己没看清，不好意思打扰了；；

**Comment by CabbCat** [comment]
不好意思又来打扰了，其他要用到群组权限的都能正常使用，但是https://github.com/Colter23/bilibili-dynamic-mirai-plugin这个插件中的top.colter.bilibili-dynamic-mirai-plugin.live.atall这条权限好像在lp中无法使用...使用mcl的权限管理正常，检查了节点名字应该也没有问题
![image](https://user-images.githubusercontent.com/37258131/155262534-411843b9-d025-46d8-a052-7ca27fcdf423.png)
开启verbose on之后在atall的消息出来之前没有这个插件权限检查相关的日志，已排除和另一个atall插件冲突的问题
