### ISSUE TITLE
部分插件权限管理和功能使用同一命令，LuckPerms拦截插件命令

### ISSUE THREAD

**Issue by DreamOneX** [Karlatemp/LuckPerms-Mirai#113]
[MShell插件](https://github.com/asforest/MShell)是一个例子，其使用/ms提供功能，同时使用/ms管理权限，安装LuckPerms后无法使用/ms

**Comment by Karlatemp** [comment]
具体问题是什么，我无法从你的问题描述中解读出问题信息

**Comment by Karlatemp** [comment]
根据此插件描述，你应该去投诉该插件作者，而不是来找 LuckPerms-Mirai
